name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        make
        echo "AMD64 build"
        make build_amd64;   mv cmsamqproxy cmsamqproxy_amd64

        echo "Darwin build"
        make build_darwin;  mv cmsamqproxy cmsamqproxy_darwin

        echo "Power8 build"
        make build_power8;  mv cmsamqproxy cmsamqproxy_power8

        echo "ARM64 build"
        make build_arm64;   mv cmsamqproxy cmsamqproxy_arm64

        echo "Windows build"
        make build_windows; mv cmsamqproxy cmsamqproxy_windows

    - name: Get the Ref
      id: get-ref
      uses: ankitvgupta/ref-to-tag-action@master
      with:
        ref: ${{ github.ref }}
        head_ref: ${{ github.head_ref }}

    - name: Build image
      run: |
        sed -i -e "s,ENV TAG=.*,ENV TAG=${{steps.get-ref.outputs.tag}},g" Dockerfile
        cat Dockerfile
        docker build . --tag registry.cern.ch/cmsweb/cmsamqproxy

    - name: Login to registry.cern.ch
      uses: docker/login-action@v1.6.0
      with:
        registry: registry.cern.ch
        username: ${{ secrets.CERN_LOGIN }}
        password: ${{ secrets.CERN_TOKEN }}

    - name: Publish image to registry.cern.ch
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CERN_LOGIN }}
        password: ${{ secrets.CERN_TOKEN }}
        registry: registry.cern.ch
        repository: cmsweb/cmsamqproxy
        tag_with_ref: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload amd64 binary
      id: upload-auth-proxy-server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsamqproxy_amd64
        asset_name: cmsamqproxy_amd64
        asset_content_type: application/octet-stream

    - name: Upload darwin binary
      id: upload-auth-proxy-server-darwin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsamqproxy_darwin
        asset_name: cmsamqproxy_darwin
        asset_content_type: application/octet-stream

    - name: Upload power8 binary
      id: upload-auth-proxy-server-power8
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsamqproxy_power8
        asset_name: cmsamqproxy_power8
        asset_content_type: application/octet-stream

    - name: Upload arm64 binary
      id: upload-auth-proxy-server-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsamqproxy_arm64
        asset_name: cmsamqproxy_arm64
        asset_content_type: application/octet-stream

    - name: Upload windows binary
      id: upload-auth-proxy-server-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsamqproxy_windows
        asset_name: cmsamqproxy_windows
        asset_content_type: application/octet-stream

#     - name: Push new image to k8s
#       run: |
#         curl -ksLO https://raw.githubusercontent.com/vkuznet/imagebot/main/imagebot.sh
#         sed -i -e "s,COMMIT,${{github.sha}},g" -e "s,REPOSITORY,${{github.repository}},g" -e "s,NAMESPACE,wma,g" -e "s,TAG,${{steps.get-ref.outputs.tag}},g" -e "s,IMAGE,registry.cern.ch/cmsweb/cmsamqproxy,g" -e "s,SERVICE,cmsamqproxy,g" -e "s,HOST,${{secrets.IMAGEBOT_URL}},g" imagebot.sh
#         chmod +x imagebot.sh
#         cat imagebot.sh
#         sh ./imagebot.sh
